# Generated by Django 2.2 on 2021-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_box_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
